// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package restapi

import (
	"bettertomorrow/context/customer/application"
)

// Injectors from wire_init.go:

func NewCustomerRouter() *CustomerRouter {
	customerServiceImpl := application.ProvideCustomerServiceImpl()
	customerWalletsServiceImpl := application.ProvideCustomerWalletsServiceImpl()
	customerRouter := instantiateCustomerRouter(customerServiceImpl, customerWalletsServiceImpl)
	return customerRouter
}

func NewWalletRouter() *WalletRouter {
	walletServiceImpl := application.ProvideWalletServiceImpl()
	walletRouter := instantiateWalletRouter(walletServiceImpl)
	return walletRouter
}
