// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package restapi

import (
	"bettertomorrow/context/employee/application"
)

// Injectors from wire_init.go:

func NewEmployeeRouter() *EmployeeRouter {
	employeeServiceImpl := application.ProvideEmployeeServiceImpl()
	employeeRolesServiceImpl := application.ProvideEmployeeRolesServiceImpl()
	employeeRouter := instantiateEmployeeRouter(employeeServiceImpl, employeeRolesServiceImpl)
	return employeeRouter
}

func NewRoleRouter() *RoleRouter {
	roleServiceImpl := application.ProvideRoleServiceImpl()
	roleRouter := instantiateRoleRouter(roleServiceImpl)
	return roleRouter
}
