// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package restapi

import (
	"bettertomorrow/context/company/application"
)

// Injectors from wireInit.go:

func NewCompanyRouter() (*CompanyRouter, error) {
	companyServiceImpl := application.ProvideCompanyServiceImpl()
	companyRouter := instantiateCompanyRouter(companyServiceImpl)
	return companyRouter, nil
}
