// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package restapi

import (
	"bettertomorrow/context/company/application"
)

// Injectors from wireInit.go:

func NewCompanyRouter() (*CompanyRouter, error) {
	companyServiceImpl := application.ProvideCompanyServiceImpl()
	companyProductsServiceImpl := application.ProvideCompanyProductsServiceImpl()
	companyRouter := instantiateCompanyRouter(companyServiceImpl, companyProductsServiceImpl)
	return companyRouter, nil
}

func NewProductRouter() (*ProductRouter, error) {
	productServiceImpl := application.ProvideProductServiceImpl()
	productRouter := instantiateProductRouter(productServiceImpl)
	return productRouter, nil
}
